AspNetBlog/AspNetBlog/Models/ErrorViewModel.cs
namespace AspNetBlog.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetBlog/AspNetBlog/Models/SliderViewModel.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.Models
{
	public class SliderViewModel
	{
		public string? Name { get; set; }
		public string? Title { get; set; }
		public string? ImageUrl { get; set; }
		public DateTime Date { get; set; }
	}
}

AspNetBlog/AspNetBlog/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.Controllers
{
	public class AuthController : Controller
	{
		public IActionResult ForgotPassword()
		{
			return View();
		}
		public IActionResult Register()
		{
			return View();
		}
		public IActionResult Login(string redirectUrl)
		{
			return View();
		}
	}
}

AspNetBlog/AspNetBlog/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.Controllers
{
	public class BlogController : Controller
	{
		public IActionResult Detail(int id)
		{
			return View();
		}
        public IActionResult Search(string query, int page)
        {
            return View();
        }
    }
}

AspNetBlog/AspNetBlog/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.Controllers
{
	public class CategoryController : Controller
	{
		public IActionResult Software(int id, int page)
		{
			return View();
		}
        public IActionResult Innovation(int id, int page)
        {
            return View();
        }
        public IActionResult Trends(int id, int page)
        {
            return View();
        }
        public IActionResult Social(int id, int page)
        {
            return View();
        }

        public IActionResult BlogSingle(int id, int page)
        {
            return View();
        }
		public IActionResult Index(int id, int page)
		{
			return View();
		}
	}
}

AspNetBlog/AspNetBlog/Controllers/HomeController.cs
using AspNetBlog.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AspNetBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AspNetBlog/AspNetBlog/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.Controllers
{
    public class PageController : Controller
    {
        public IActionResult Detail(int id)
        {
            return View();
        }
		public IActionResult Contact()
		{
			return View();
		}
	}
}

AspNetBlog/AspNetBlog/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.Controllers
{
    public class PostController : Controller
    {
        public IActionResult Video()
        {
            return View();
        }
        public IActionResult Audio()
        {
            return View();
        }
        public IActionResult Quote()
        {
            return View();
        }
        public IActionResult Gallery()
        {
            return View();
        }
        public IActionResult Image()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetBlog/AspNetBlog/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {

            return View();

        }
    }
}

AspNetBlog/AspNetBlog/ViewComponents/NavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.ViewComponents
{
    public class NavBarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {

            return View();

        }
    }
}

AspNetBlog/AspNetBlog/ViewComponents/SideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.ViewComponents
{
	public class SideBarViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{

			return View();

		}
	}
}

AspNetBlog/AspNetBlog/ViewComponents/SliderViewComponent.cs
using AspNetBlog.Models;
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.ViewComponents
{
	public class SliderViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			var SliderItems = new List<SliderViewModel>
			{
				new SliderViewModel
				{
					Date = DateTime.Now,
					Name = "Trip to California",
					Title= "Social",
					ImageUrl= "/images/slider/slider1.jpg"
				},
				new SliderViewModel
				{
					Date = DateTime.Now,
					Name = "Our Favorite Weekend Getaways",
					Title= "Innovation",
					ImageUrl= "/images/slider/slider3.jpg"
				},
				new SliderViewModel
				{
					Date = DateTime.Now,
					Name = "Tips for Taking a Long-term Trip",
					Title= "Trends",
					ImageUrl= "/images/slider/slider2.jpg"
				},
				new SliderViewModel
				{
					Date = DateTime.Now,
					Name = "Tips for Taking a Long-term Trip",
					Title= "Software",
					ImageUrl= "/images/slider/slider1.jpg"
				},
				new SliderViewModel
				{
					Date = DateTime.Now,
					Name = "Tips for Taking a Long-term Trip",
					Title= "Software",
					ImageUrl= "/images/slider/slider2.jpg"
				},
			};

			return View(SliderItems);
		}
	}
}

AspNetBlog/AspNetBlog/ViewComponents/SubscribeViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetBlog.ViewComponents
{
    public class SubscribeViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {

            return View();

        }
    }
}

AspNetBlog/AspNetBlog/Views/Category/Index.cshtml
<ul class="list-group" >
    <li class="list-group-item"><a href="@Url.Action("Innovation","Category")">Innovation</a></li>
    <li class="list-group-item"><a href="@Url.Action("Social","Category")">Social</a></li>
    <li class="list-group-item"><a href="@Url.Action("Software","Category")">Software</a></li>
    <li class="list-group-item"><a href="@Url.Action("Trends","Category")">Trends</a></li>

</ul>

AspNetBlog/AspNetBlog/Views/Page/Contact.cshtml
<div class="breadcrumb-wrapper">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<div class="text-center">
					<h2 class="lg-title">Contact</h2>
				</div>
			</div>
		</div>
	</div>
</div>

<section class="pt-5 padding-bottom">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">


				<div class="row">
					<div class="col-lg-12">
						<img src="..//images/contact.jpg" alt="" class="img-fluid w-100">
					</div>
				</div>

				<div class="row justify-content-center">
					<div class="col-lg-8">
						<p class="mt-5 mb-5">Something splashing about in the pool a little way off, and she swam nearer to make out what it was: at first she thought it must be a walrus or hippopotamus, but then she remembered how small she was now, and she soon made out that it was only a mouse that had slipped in like herself.</p>

						<h2 class="mb-4">Get In Touch</h2>

						<form id="contact-form" class="contact-form">
							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<label for="name">Your Name (required)</label>
										<input class="form-control form-control-name" name="name" id="name" type="text" required>
									</div>

									<div class="form-group">
										<label for="email">Your Email (required)</label>

										<input class="form-control form-control-email" name="email" id="email" type="email" required>
									</div>

									<div class="form-group">
										<label for="message">Your Message</label>
										<textarea class="form-control form-control-message" name="message" id="message" rows="7" required></textarea>
									</div>

									<button class="btn btn-primary solid blank mt-3" type="submit">Send Message</button>
								</div>
							</div>
						</form>
					</div>
				</div>




			</div>
		</div>
	</div>
</section>

AspNetBlog/AspNetBlog/Views/Post/Index.cshtml
<ul class="list-group">
    <li class="list-group-item"><a href="@Url.Action("Audio","Post")">Audio</a></li>
    <li class="list-group-item"><a href="@Url.Action("Gallery","Post")">Gallery</a></li>
    <li class="list-group-item"><a href="@Url.Action("Image","Post")">Image</a></li>
    <li class="list-group-item"><a href="@Url.Action("Quote","Post")">Quote</a></li>
    <li class="list-group-item"><a href="@Url.Action("Video","Post")">Video</a></li>

</ul>

AspNetBlog/AspNetBlog/Views/Shared/Components/Footer/Default.cshtml
@{
    ViewData["Title"] = "Default";
}
<!DOCTYPE html>
<html lang="en">
<body>

	<section class="footer-2 section-padding gray-bg pb-5">
		<div class="container">
			<div class="footer-btm mt-5 pt-4 border-top">
				<div class="row">
					<div class="col-lg-12">
						<ul class="list-inline footer-socials-2 text-center">
							<li class="list-inline-item"><a href="#">Privacy policy</a></li>
							<li class="list-inline-item"><a href="#">Support</a></li>
							<li class="list-inline-item"><a href="@Url.Action("Detail","Page")">About</a></li>
							<li class="list-inline-item"><a href="@Url.Action("Contact","Page")">Contact</a></li>
							<li class="list-inline-item"><a href="#">Terms</a></li>
							<li class="list-inline-item"><a href="@Url.Action("Index","Category")">Category</a></li>
						</ul>
					</div>
				</div>
				<div class="row justify-content-center">
					<div class="col-lg-6">
						<div class="copyright text-center ">
							@@ copyright all reserved to <a href="https://themefisher.com/">themefisher.com</a>-2019
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</body>

</html>

AspNetBlog/AspNetBlog/Views/Shared/Components/NavBar/Default.cshtml
@{
    ViewData["Title"] = "Default";
}

<!DOCTYPE html>
<html lang="en">
<header class="header-top bg-grey justify-content-center">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-2 col-md-4 text-center d-none d-lg-block">
                <a href="@Url.Action("Index", "Home")">
                    <img src="..//images/logo.png" alt="" class="img-fluid">
                </a>
            </div>
            <div class="col-lg-8 col-md-12">
                <nav class="navbar navbar-expand-lg navigation-2 navigation">
                    <a class="navbar-brand text-uppercase d-lg-none" href="#">
                        <img src="images/logo.png" alt="" class="img-fluid">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="ti-menu"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar-collapse">
                        <ul id="menu" class="menu navbar-nav mx-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Home
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="@Url.Action("Index","Home")">HomePage</a>

                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Blog Posts
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                    <a href="@Url.Action("Detail", "Blog")">Blog Details</a>
                                    <a href="@Url.Action("Search","Blog")">Blog Search</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Detail","Page")" class="nav-link">About</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="@Url.Action("Index","Category")" class="nav-link">Category</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                    <a asp-action="Innovation" asp-controller="Category">Innovation</a>
                                    <a asp-action="Software" asp-controller="Category">Software</a>
                                    <a asp-action="Social" asp-controller="Category">Social</a>
                                    <a asp-action="Trends" asp-controller="Category">Trends</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="@Url.Action("Index","Post")" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Post Format
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                                    <a class="dropdown-item" href="@Url.Action("Video","Post")">Video Formats</a>
                                    <a class="dropdown-item" href="@Url.Action("Audio","Post")">Audio Format</a>
                                    <a class="dropdown-item" href="@Url.Action("Quote","Post")">Quote Format</a>
                                    <a class="dropdown-item" href="@Url.Action("Gallery","Post")">Gallery Format</a>
                                    <a class="dropdown-item" href="@Url.Action("Image","Post")">Image Format</a>
                                </div>

                            </li>
                            <li class="nav-item"><a href="@Url.Action("Contact","Page")" class="nav-link">Contact</a></li>
                        </ul>
                        @* Register and Login*@
                        <div class="dropdown">
                            <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="material-symbols-outlined">person</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="@Url.Action("Register","Auth")">Register</a>
                                <a class="dropdown-item" href="@Url.Action("Login","Auth")">Login</a>
                            </div>
                        </div>

                        <div class="nav-item">
                            <a class="nav-link">
                                <div class="text-right search d-none d-lg-block">
                                    <div class="search_toggle"><i class="ti-search"></i></div>
                                </div>
                            </a>
                        </div>


                    </div>
                </nav>
            </div>


            <div class="col-lg-2 col-md-4 col-6">
                <div class="header-socials-2 text-right d-none d-lg-block">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item"><a href="https://www.facebook.com/profile.php?id=100006700939116"><i class="ti-facebook"></i></a></li>
                        <li class="list-inline-item"><a href="https://www.linkedin.com/in/sena-polen-tunc/"><i class="ti-linkedin"></i></a></li>
                        <li class="list-inline-item"><a href="https://github.com/Ptunc"><i class="ti-github"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>
<body>
</body>

</html>

AspNetBlog/AspNetBlog/Views/Shared/Components/Slider/Default.cshtml
@model List<SliderViewModel>

<section class="slider mt-4">
    <div class="container-fluid">
        <div class="row no-gutters">
            <div class="col-lg-12 col-sm-12 col-md-12 slider-wrap">
                @foreach (var item in Model)
                {
                    <div class="slider-item">
                        <div class="slider-item-content">
                            <div class="post-thumb mb-4">
                                <a href="@Url.Action("BlogSingle", "Category")">
                                    <img src=@item.ImageUrl alt="" class="img-fluid">
                                </a>
                            </div>
                            <div class="slider-post-content">
                                <span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">@item.Title</span>
                                <h3 class="post-title mt-1"><a href="@Url.Action("BlogSingle", "Category")">@item.Name</a></h3>
                                <span class=" text-muted  text-capitalize">@item.Date</span>
                            </div>
                        </div>
                    </div>
                }
                <ul class="slick-dots" style="display: block;" role="tablist"><li class="" role="presentation"><button type="button" role="tab" id="slick-slide-control00" aria-controls="slick-slide00" aria-label="1 of 3" tabindex="-1">1</button></li><li role="presentation" class=""><button type="button" role="tab" id="slick-slide-control01" aria-controls="slick-slide02" aria-label="2 of 3" tabindex="-1">2</button></li><li role="presentation" class="slick-active"><button type="button" role="tab" id="slick-slide-control02" aria-controls="slick-slide04" aria-label="3 of 3" tabindex="-1">3</button></li></ul>
                <ul class="slick-dots" style="display: block;" role="tablist"><li class="" role="presentation"><button type="button" role="tab" id="slick-slide-control00" aria-controls="slick-slide00" aria-label="1 of 3" tabindex="-1">1</button></li><li role="presentation" class=""><button type="button" role="tab" id="slick-slide-control01" aria-controls="slick-slide02" aria-label="2 of 3" tabindex="-1">2</button></li><li role="presentation" class="slick-active"><button type="button" role="tab" id="slick-slide-control02" aria-controls="slick-slide04" aria-label="3 of 3" tabindex="-1">3</button></li></ul>
            </div>
        </div>
    </div>
</section>

AspNetBlog/AspNetBlog/Views/Shared/Components/Subscribe/Default.cshtml
@{
	ViewData["Title"] = "Default";
}
<!DOCTYPE html>
<html lang="en">
<body>

	<section class="footer-2 section-padding gray-bg pb-5">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-6">
					<div class="subscribe-footer text-center">
						<div class="form-group mb-0">
							<h2 class="mb-3">Subscribe Newsletter</h2>
							<p class="mb-4">Subscribe my Newsletter for new blog posts , tips and info.
							<p>
								<div class="form-group form-row align-items-center mb-0">
									<div class="col-sm-9">
										<input type="email" class="form-control" placeholder="Email Address">
									</div>
									<div class="col-sm-3">
										<a href="#" class="btn btn-dark ">Subscribe</a>
									</div>
								</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</section>
</body>

</html>

AspNetBlog/AspNetBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Revolve - Personal Magazine Blog Template</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--Favicon-->
    <link rel="shortcut icon" href="..//images/favicon.ico" type="image/x-icon">
    <!-- THEME CSS
    ================================================== -->
    <!-- Bootstrap -->

    <link rel="stylesheet" href="..//plugins/bootstrap/css/bootstrap.min.css">
    <!-- Themify -->
    <link rel="stylesheet" href="..//plugins/themify/css/themify-icons.css">
    <link rel="stylesheet" href="..//plugins/slick-carousel/slick-theme.css">
    <link rel="stylesheet" href="..//plugins/slick-carousel/slick.css">
    <!-- Slick Carousel -->
    <link rel="stylesheet" href="..//plugins/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="..//plugins/owl-carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="..//plugins/magnific-popup/magnific-popup.css">
    <!-- manin stylesheet -->
    <link rel="stylesheet" type="text/css" href="~/css/StyleSheet.css">
    <link rel="stylesheet" href="..//css/style.css">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
</head>
<body>

    @* Partials*@

    @await Component.InvokeAsync("NavBar")
    @await Component.InvokeAsync("Slider")

    @RenderBody()
    @await Component.InvokeAsync("Subscribe")
    @await Component.InvokeAsync("Footer")


    @* Scripts*@
    <script src="..//plugins/jquery/jquery.js"></script>
    <!-- Bootstrap jQuery -->
    <script src="..//plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="..//plugins/bootstrap/js/popper.min.js"></script>
    <!-- Owl caeousel -->
    <script src="..//plugins/owl-carousel/owl.carousel.min.js"></script>
    <script src="..//plugins/slick-carousel/slick.min.js"></script>
    <script src="..//plugins/magnific-popup/magnific-popup.js"></script>
    <!-- Instagram Feed Js -->
    <script src="..//plugins/instafeed-js/instafeed.min.js"></script>
    <!-- Google Map -->
    <script src="..//maps/api/js_key_AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw.js"></script>
    <script src="..//plugins/google-map/gmap.js"></script>
    <!-- main js -->
    <script src="..//js/custom.js"></script>

</body>
</html>

AspNetBlog/AspNetBlog/Views/Shared/_NavBarPartialView.cshtml
@{
}
<!DOCTYPE html>
<html lang="en">
<header class="header-top bg-grey justify-content-center">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-2 col-md-4 text-center d-none d-lg-block">
                <a class="navbar-brand " href="index.html">
                    <img src="..//images/logo.png" alt="" class="img-fluid">
                </a>
            </div>
            <div class="col-lg-8 col-md-12">
                <nav class="navbar navbar-expand-lg navigation-2 navigation">
                    <a class="navbar-brand text-uppercase d-lg-none" href="#">
                        <img src="images/logo.png" alt="" class="img-fluid">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="ti-menu"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar-collapse">
                        <ul id="menu" class="menu navbar-nav mx-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Home
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="@Url.Action("Index","Home")">HomePage</a>

                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Blog Posts
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                    <a href="@Url.Action("Detail", "Blog")">Blog Details</a>
                                    <a href="@Url.Action("Search","Blog")">Blog Search</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Detail","Page")" class="nav-link">About</a>
                            </li>
                            <li class="nav-item"><a href="@Url.Action("Index","Category")" class="nav-link">Category</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Post Format
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                                    <a class="dropdown-item" href="post-video.html">Video Formats</a>
                                    <a class="dropdown-item" href="post-audio.html">Audio Format</a>
                                    <a class="dropdown-item" href="post-link.html">Quote Format</a>
                                    <a class="dropdown-item" href="post-gallery.html">Gallery Format</a>
                                    <a class="dropdown-item" href="post-image.html">Image Format</a>
                                </div>

                            </li>
                            <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
                        </ul>
                        @* Register and Login*@
                        <div class="dropdown">
                            <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="material-symbols-outlined">person</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="@Url.Action("Register","Auth")">Register</a>
                                <a class="dropdown-item" href="@Url.Action("Login","Auth")">Login</a>
                            </div>
                        </div>



                        <ul class="list-inline mb-0 d-block d-lg-none">
                            <li class="list-inline-item"><a href="#"><i class="ti-facebook"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="ti-twitter"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="ti-linkedin"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="ti-pinterest"></i></a></li>
                            <li class="list-inline-item"><a href="@Url.Action("Auth","Register")">Register</a></li>

                        </ul>

                    </div>
                </nav>
            </div>
            <div class="col-lg-2 col-md-4 col-6">
                <div class="header-socials-2 text-right d-none d-lg-block">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item"><a href="#"><i class="ti-facebook"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="ti-twitter"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="ti-linkedin"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="ti-pinterest"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>
<body>
</body>

</html>